### ISSUE TITLE
Guidelines are not appearing correctly in OSX dark-mode when using Edge

### ISSUE THREAD

**Issue by bnjmnrsh** [KittyGiraudel/sass-guidelines#525]
Hi all,

Just an fyi that on OSX with Edge, when I set the OS to dark mode, Im seeing an issue where the primary text is dark-on-dark, but only on incognito tabs, and only in Edge, not chrome. ... so weird!

Screenshot left is a normal tab, right is an incognito tab.

![Screenshot 2021-11-15 at 17 40 33](https://user-images.githubusercontent.com/65979639/141828977-68fe90b0-a67a-45c7-9523-d0358acdffe9.png)

**Comment by KittyGiraudel** [comment]
Hello! Thank you for the report. I can only assume it’s an issue related to an accessibility/theming feature from Edge. I’ll have to install it to investigate.

**Comment by KittyGiraudel** [comment]
Thank you for the report!
