### ISSUE TITLE
"Undefined variable" 

### ISSUE THREAD

**Issue by MahendraBishnoi29** [KittyGiraudel/sass-guidelines#530]
**This Is The Issue , I've Imported All the files correctly but still i'm getting this error**
![Screenshot (84)](https://user-images.githubusercontent.com/74294202/148916439-a88ab4d2-f02f-417b-952f-9a5fd8d73645.png)

**My Folder Structure**
![Screenshot (85)](https://user-images.githubusercontent.com/74294202/148916455-3dbe96bc-5b05-4b77-90d2-2d9d8f95ba13.png)

**Comment by KittyGiraudel** [comment]
Hello. This repository is about the Sass Guidelines themselves, which do not mandate any variable, so I’m not sure what I can do to help. Especially without having access to any code — there is only so much I can see from screenshots. Please, kindly move that question to StackOverflow, ideally with a reproducible test case so people can help.

**Comment by MahendraBishnoi29** [comment]
> Hello. This repository is about the Sass Guidelines themselves, which do not mandate any variable, so I’m not sure what I can do to help. Especially without having access to any code — there is only so much I can see from screenshots. Please, kindly move that question to StackOverflow, ideally with a reproducible test case so people can help.

thank you so much for replying, actually the problem was in my folder so i solved it.
Also I'm really sorry to post this question here i didn't knew that it's just for guidelines and issues, hope you understand :)

**Comment by KittyGiraudel** [comment]
I’m glad you solved it. Cheers!
