### ISSUE TITLE
Singularity grid system is obsolete, must be removed from guidelines

### ISSUE THREAD

**Issue by Klemart3D** [KittyGiraudel/sass-guidelines#548]
[Singularity](https://github.com/at-import/Singularity) (named in [Tools > Grid system part](https://sass-guidelin.es/#grid-systems)) is no more maintained, it must be removed from guidelines and use [CSS Grid Layout](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout) instead. Source : https://snugug.com/musings/saying-goodbye-to-singularity/

**Comment by KittyGiraudel** [comment]
Done with https://github.com/KittyGiraudel/sass-guidelines/commit/c8c2cea0ee976a9680e36d02a3a1106dcf4c419b. Thanks!

**Comment by Klemart3D** [comment]
Thank Kitty but I meant in Grid System text part for all langauges, eg. for english:
https://github.com/KittyGiraudel/sass-guidelines/blob/c8c2cea0ee976a9680e36d02a3a1106dcf4c419b/pages/en/_tools.md?plain=1#L32

**Comment by KittyGiraudel** [comment]
Thanks, I messed up my code search and missed a lot of cases.

**Comment by Pasqualle** [comment]
Susy is also deprecated https://www.oddbird.net/susy/
The whole "Grid systems" section should be updated.

**Comment by Klemart3D** [comment]
And the [last version of csswizardry-grids](https://github.com/csswizardry/csswizardry-grids/tree/v2.2.0) have almost 10 years with no significant update since then so I'm not sure to mention it in guidelines is good idea.
Grid systems tools/dependencies no longer seem useful since CSS3, I rename my issue.
