### ISSUE TITLE
Grammatical change at #numbers-1

### ISSUE THREAD

**Issue by ItsFrankieD** [KittyGiraudel/sass-guidelines#573]
`Sass makes no distinction between numbers, integers, floats so trailing zeros (0) should be omitted.` should read `Sass makes no distinction between numbers, integers, and floats, so trailing zeros (0) should be omitted.`

**Comment by KittyGiraudel** [comment]
Good catch! If you’d like to issue a pull-request, I’ll merge it. :)

**Comment by ItsFrankieD** [comment]
Thanks! It may take me a moment, as I've never made a contribution on GitHub. Time to start Googling!
